version: '3'
services:    
    postgres_db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    # api server    
    api:
        build:
          context: ./
          dockerfile: Dockerfile
        image: "charumathyp/api1" 
        ports:
          - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres_db
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
            